from rsf.proj import *
import wplot, pplot

from random import random

import numpy as np
np.random.seed(2024)

VERB      = False # verbose mode
PLOT      = False #    plot mode

AMPLITUDE = True  # add amplitude variation
CURVATURE = True  # add curvature

# ------------------------------------------------------------
# global parameters
par = dict( nt=512,  ot=+0.0,     dt=0.0892857,     lt='t',   ut='us',
            nx=512,  ox=-1000.0,  dx=4.00,     lx='x',   ux='.',
            verb='y'
        )
par['fPeak']  = 4.0 # [MHz] wavelet peak frequency
par['fBand']  = 1.0 # [MHz] wavelet frequency band

wplot.param(par)
wplot.dgrey2d_init(250.0,par)
par['dheight2d'] = 11
par['labelattr'] += ' labelsz=5 labelfat=2 '

# ------------------------------------------------------------
# ------------------------------------------------------------
nr =  64 # number of realizations
nc =   3 # number of carriers
nk = [int(1+3*random()) for r in range(nr)]
total = sum(nk)

# time
tcen = par['ot'] + (par['nt']-1)/2 * par['dt']
tsig =             (par['nt']-1)/8 * par['dt']
tx = np.random.normal( tcen, tsig, total)
if VERB: print(tx)

# slope
pcen = 0.000
psig = 0.002
px = np.random.normal( pcen, psig, total)
if VERB: print(px)

# amplitude
if AMPLITUDE:
    acen = 0.00
    asig = 1.0e-3
    ax = np.random.normal( acen, asig, total)
else:
    ax = np.ones(total)
if VERB: print(ax)

# curvature amplitude
if CURVATURE:
    wcen = 0.00
    wsig = 0.25
    wx = np.random.normal( wcen, wsig, total)
else:
    wx = np.zeros(total)
if VERB: print(wx)

# curvature frequency
if CURVATURE:
    fcen = 0.0
    fsig = 1.0e-3
    fx = np.random.normal( fcen, fsig, total)
else:
    fx = np.zeros(total)
if VERB: print(fx)

# ------------------------------------------------------------
# ------------------------------------------------------------
# make data

nt_min = 450; nt_max = 512
nx_min = 450; nx_max = 512

max_power2 = 512

for jr in range(nr): # loop over realizations
    rtag = "-r%03d"%jr

    # generate random dimensions
    par['nt'] = nt_min + (nt_max - nt_min) * random()
    par['nx'] = nx_min + (nx_max - nx_min) * random()

    for k in range(nk[jr]):

        prev = sum(nk[:jr]) + k

        comptag = "%d"%k

        for ic in range(nc): # loop over carriers
            ctag = "%d"%ic

            fPeak = par['fPeak'] / np.power(2,ic)

            Flow('comp'+comptag+ctag+rtag,None,
                '''  
                math n1=%d o1=%g d1=%g label1=%s unit1=%s
                    n2=%d o2=%g d2=%g label2=%s unit2=%s
                output="cos( 2 * (%g)   * (%g)   * (x1 - (%g) + (%g) * x2 + (%g)*cos(2*(%g) * x2*(%g)) )  ) *
                        exp(-2 * (%g)^2 * (%g)^2 * (x1 - (%g) + (%g) * x2 + (%g)*cos(2*(%g) * x2*(%g)) )^2) * 
                        (1.0 + 0.5 * cos(2*(%g) * x2*(%g)))" | 
                scale %g |
                pad end1=%d end2=%d
                '''%( par['nt'],par['ot'],par['dt'],par['lt'],par['ut'],
                        par['nx'],par['ox'],par['dx'],par['lx'],par['ux'],
                        np.pi, fPeak,          tx[prev], px[prev], wx[prev], np.pi, fx[prev],
                        np.pi, par['fBand']/4, tx[prev], px[prev], wx[prev], np.pi, fx[prev],
                        np.pi, ax[prev], 
                        random(),
                        max_power2-par['nt']+1, max_power2-par['nx']+1
                    ) 
                )
            
    c0 = ' '.join(['comp'+f'{k}'+ '0' + rtag + '.rsf' for k in range(nk[jr])])
    c1 = ' '.join(['comp'+f'{k}'+ '1' + rtag + '.rsf' for k in range(nk[jr])])
    c2 = ' '.join(['comp'+f'{k}'+ '2' + rtag + '.rsf' for k in range(nk[jr])])
    carrier_strings = (c0, c1, c2)

    f0 = 'dat'+'0'+rtag
    f1 = 'dat'+'1'+rtag
    f2 = 'dat'+'2'+rtag
    final_strings = (f0, f1, f2)

    for c, f in zip(carrier_strings, final_strings):
        seed, rng, var = jr*nr+ic, 0.05, 0.1, 
        Flow(f, None, f'add {c} | noise seed={seed} range={rng} var={var}')

# ------------------------------------------------------------
# ------------------------------------------------------------
# concatenate data

for ic in range(nc): # loop over carriers
    ctag = "%d"%ic

    Flow('dat'+ctag,['dat'+ctag+"-r%03d"%jr for jr in range(nr)],
        'cat axis=3 space=n ${SOURCES[1:%d]}'%nr)
    
    Flow('byt'+ctag,'dat'+ctag,'byte gainpanel=a pclip=100')

# ------------------------------------------------------------
# ------------------------------------------------------------
# plot data

if PLOT:
    for jr in range(nr): # loop over realizations
        rtag = "-r%03d"%jr

        for ic in range(nc): # loop over carriers
            ctag = "%d"%ic

            if ic == 0: Plot('dat'+ctag+rtag,'byt'+ctag,
                                'window n3=1 f3=%d |'%jr + 
                                wplot.dgrey2d('grid=y',par))
            else:       Plot('dat'+ctag+rtag,'byt'+ctag,
                                'window n3=1 f3=%d |'%jr + 
                                wplot.dgrey2d('wantaxis=n',par))

        pplot.multip('dat'+rtag,['dat0'+rtag,'dat1'+rtag,'dat2'+rtag],1,3, 1.0,1.0, 0.0,-3.75)
        Result('dat'+rtag,'dat'+rtag,'Overlay')

End()
